### ISSUE TITLE
综合成本大概多少？

### ISSUE THREAD

**Issue by denghailong123** [WangXuan95/UniPlug-FPGA#1]
如果在预算之内打算打一个

**Comment by WangXuan95** [comment]
你好，
在2020年前（芯片涨价前），如果接受二手翻新芯片：

- 样板（≤10pcs）成本 ￥40/pcs
- 大批量（≥100pcs）成本 ￥30/pcs

在2020年后，价格就比较魔幻了，甚至能 ￥200/pcs
